const qs=new URLSearchParams(location.search),access=qs.get("access")||"",state={config:null,data:null,rows:[],focused:null};
const $=id=>document.getElementById(id),esc=v=>String(v??"—").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
const map=L.map("map",{zoomControl:true}).setView([12.56,104.99],7);
L.tileLayer("https://server.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer/tile/{z}/{y}/{x}",{maxZoom:19,attribution:"Imagery © Esri"}).addTo(map);
L.tileLayer("https://services.arcgisonline.com/ArcGIS/rest/services/Reference/World_Boundaries_and_Places/MapServer/tile/{z}/{y}/{x}",{maxZoom:19,attribution:"Boundaries © Esri"}).addTo(map);
const markers=L.layerGroup().addTo(map);
function api(path,params={}){const p=new URLSearchParams({...params,access});return fetch(`${path}?${p}`).then(async r=>{const j=await r.json().catch(()=>({}));if(!r.ok)throw Error(j.detail||"Request failed");return j})}
function options(el,values,all){el.innerHTML=`<option value="">${all}</option>`+values.map(v=>`<option value="${esc(v)}">${esc(v)}</option>`).join("")}
function dealers(){const r=$("region").value;return r?(state.config.regions[r]||[]):[...new Set(Object.values(state.config.regions).flat())].sort()}
function updateDealers(){options($("dealer"),dealers(),"All dealers")}
async function init(){try{state.config=await api("/api/map/filters");options($("region"),Object.keys(state.config.regions),"All regions");updateDealers();options($("category"),state.config.categories,"All categories");options($("product"),state.config.products,"All products");await load()}catch(e){showError(e.message)}}
function params(){const [min,max]=$("movement").value.split(",");return{region:$("region").value,dealer:$("dealer").value,report_date:$("reportDate").value,category:$("category").value,product:$("product").value,movement_min:min,movement_max:max}}
async function load(){showError("Loading survey movement…");try{state.data=await api("/api/map/data",params());state.rows=state.data.rows;state.focused=null;render();$("message").classList.add("hidden")}catch(e){showError(e.message)}}
function showError(text){$("message").textContent=text;$("message").classList.remove("hidden")}
function markerIcon(row){return L.divIcon({className:"",html:`<div style="width:38px;height:38px;display:grid;place-items:center;border:3px solid white;border-radius:50%;color:white;background:${row.movement_color};box-shadow:0 3px 10px #0007;font-weight:800">${row.movement_score}</div>`,iconSize:[38,38],iconAnchor:[19,19]})}
function render(){markers.clearLayers();const bounds=[];state.rows.forEach((r,i)=>{const angle=(i%12)*Math.PI/6,offset=(i%4)*.00004,lat=r.latitude+Math.sin(angle)*offset,lng=r.longitude+Math.cos(angle)*offset;const m=L.marker([lat,lng],{icon:markerIcon(r)}).addTo(markers);m.bindPopup(`<div class="popup"><h3>${esc(r.outlet_name)}</h3><p>${esc(r.outlet_type)} · ${esc(r.region)} / ${esc(r.dealer)}</p><p><b>${esc(r.product)}</b> (${esc(r.product_source)})</p><p class="rating" style="color:${r.movement_color}">${r.movement_score} / 10</p><p>${esc(r.key_issue)}</p><a target="_blank" href="https://www.google.com/maps/dir/?api=1&destination=${r.latitude},${r.longitude}">Navigate</a></div>`);m.on("click",()=>focus(r.id));bounds.push([lat,lng])});if(bounds.length)map.fitBounds(bounds,{padding:[45,45],maxZoom:15});else map.setView([12.56,104.99],7);renderStats();renderRows(state.rows);renderDashboard()}
function renderStats(){const s=state.data.summary;$("mapStats").innerHTML=`<div><strong>${s.total_outlets}</strong><small>Outlets</small></div><div><strong>${s.total_ratings}</strong><small>Product ratings</small></div><div><strong>${s.very_strong}</strong><small>Very strong</small></div><div><strong>${s.with_issue}</strong><small>With issue</small></div>`}
function renderRows(rows){$("listTitle").textContent=`OUTLET & PRODUCT LIST (${rows.length} ratings)`;$("showAll").classList.toggle("hidden",!state.focused);$("rows").innerHTML=rows.map(r=>`<tr data-id="${esc(r.id)}"><td>${esc(r.outlet_name)}</td><td>${esc(r.outlet_type)}</td><td>${esc(r.phone_number)}</td><td>${esc(r.region)}</td><td>${esc(r.dealer)}</td><td>${esc(r.product)}</td><td>${r.product_source==="own"?"Own":"Competitor"}</td><td>${esc(r.category)}</td><td>${esc(r.stock_status)}</td><td>${esc(r.key_issue)}</td><td><span class="score" style="background:${r.movement_color}">${r.movement_score}</span></td><td>${esc(r.report_date)}</td><td><a class="nav-link" target="_blank" href="https://www.google.com/maps/dir/?api=1&destination=${r.latitude},${r.longitude}">Navigate</a></td></tr>`).join("");document.querySelectorAll("#rows tr").forEach(tr=>tr.onclick=()=>focus(tr.dataset.id))}
function focus(id){state.focused=id;const row=state.rows.find(r=>r.id===id);if(!row)return;renderRows([row]);map.flyTo([row.latitude,row.longitude],16);document.querySelector(".list-panel").scrollIntoView({behavior:"smooth",block:"start"})}
function renderDashboard(){const s=state.data.summary,cards=[["Total Outlets",s.total_outlets],["Product Ratings",s.total_ratings],["Own Wins (10)",s.own_wins_10],["Competitor Wins (10)",s.competitor_wins_10],["Very Strong",s.very_strong],["With Key Issue",s.with_issue]];$("dashCards").innerHTML=cards.map(([l,v])=>`<article class="dash-card"><small>${l}</small><strong>${v}</strong></article>`).join("");const max=Math.max(...Object.values(s.by_score),1);$("scoreChart").innerHTML=Object.entries(s.by_score).map(([k,v])=>`<div class="bar"><b>${k}</b><div class="track"><i style="width:${v/max*100}%"></i></div><span>${v}</span></div>`).join("");const winMax=Math.max(s.own_wins_10,s.competitor_wins_10,1);$("winChart").innerHTML=`<div class="win-row"><b>Own products: ${s.own_wins_10}</b><div><i style="width:${s.own_wins_10/winMax*100}%;background:#15803d"></i></div></div><div class="win-row"><b>Competitors: ${s.competitor_wins_10}</b><div><i style="width:${s.competitor_wins_10/winMax*100}%;background:#f59e0b"></i></div></div>`;$("selectionSummary").innerHTML=`<p><b>Date:</b> ${$("reportDate").value||"All dates"}</p><p><b>Region:</b> ${$("region").value||"All regions"}</p><p><b>Dealer:</b> ${$("dealer").value||"All dealers"}</p><p><b>Product:</b> ${$("product").value||"All products"}</p>`}
function view(name){const dash=name==="dashboard";$("mapView").classList.toggle("hidden",dash);$("dashboardView").classList.toggle("hidden",!dash);$("mapTab").classList.toggle("active",!dash);$("dashboardTab").classList.toggle("active",dash);if(!dash)setTimeout(()=>map.invalidateSize(),50)}
$("region").onchange=updateDealers;$("apply").onclick=load;$("refresh").onclick=load;$("reset").onclick=()=>{["reportDate","region","dealer","category","product"].forEach(id=>$(id).value="");$("movement").value="0,10";updateDealers();load()};$("showAll").onclick=()=>{state.focused=null;renderRows(state.rows)};$("mapTab").onclick=()=>view("map");$("dashboardTab").onclick=()=>view("dashboard");$("filterToggle").onclick=()=>$("filters").classList.add("open");$("filterClose").onclick=()=>$("filters").classList.remove("open");
if(location.pathname.includes("dashboard")||qs.get("view")==="dashboard")view("dashboard");init();
